/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.concurrent.ThreadLocalRandom;
import com.tcs.tallerListas.beans.Estudiante;


public class IngresoEstudiantes {

	public static void main(String[] args) {
		
		ArrayList<Estudiante> arrayEst = new ArrayList<Estudiante>();
		ArrayList<Estudiante> arrayJardin = new ArrayList<Estudiante>();
		ArrayList<Estudiante> arrayPrimero = new ArrayList<Estudiante>();
		ArrayList<Estudiante> arraySegundo = new ArrayList<Estudiante>();
		ArrayList<Estudiante> arrayTercero = new ArrayList<Estudiante>();
		ArrayList<Estudiante> arrayCuarto = new ArrayList<Estudiante>();
		ArrayList<Estudiante> arrayQuinto = new ArrayList<Estudiante>();
		
		 
		
		System.out.println("################ Ingreso de estudiantes ################");
		
		try {
			Scanner data = new Scanner(new File("src/main/resources/data.txt"));
			
			while (data.hasNextLine()) {
				
				
				String[] estData = data.nextLine().split(",");
				 
				Estudiante estudiante = new Estudiante();
				estudiante.setId(estData[0]);
				estudiante.setNombre(estData[1]);
				estudiante.setEdad(Integer.parseInt(estData[2]));
				estudiante.setGrado(estData[3]);
				
				
				int longitud = 1;
				//genera aleatorio para saber si aprobó o reprobó
				String cadena = cadenaAleatoria(longitud);
				
				estudiante.setAprobo(cadena);
				
			
				
				arrayEst.add(estudiante);
				switch (estudiante.getGrado()) {
					case "Jardin":
						arrayJardin.add(estudiante);
						break;
					case "Primero":
						arrayPrimero.add(estudiante);
						break;
					case "Segundo":
						arraySegundo.add(estudiante);
						break;
					case "Tercero":
						arrayTercero.add(estudiante);
						break;
					case "Cuarto":
						arrayCuarto.add(estudiante);
						break;
					case "Quinto":
						arrayQuinto.add(estudiante);
						break;
					
				}
				
				
			}
			
			//Se cierra el scanner
			data.close();

		} catch (FileNotFoundException e) {
			System.out.println("El archivo no se encuentra " + e);
		}
		catch (NumberFormatException e) {
			System.out.println("La edad no puede ser alfanumerica " + e);
		}
		
		//Imprime mensajes informativos
		imprimirMensajes(arrayEst);
		
		//Imprime estudiantes por grado
		estudiantesPorGrado(arrayJardin, arrayPrimero, arraySegundo, arrayTercero, arrayCuarto, arrayQuinto);
		
		//crea nuevo campo en archivo
		actualizarArchivo(arrayEst);
		
		//imprime estudiantes que reprueban el año
		estudiantesQueReprueban(arrayEst);
				
		
			}
	
	public static void imprimirMensajes (ArrayList<Estudiante> arrayEst) {
		Integer est6y10 = 0;
		Integer totalEst = 0;
		
		System.out.println("################ Estudiantes con Tarjeta de Identidad ################");
		for (int i = 0;i< arrayEst.size();i++) { 
			Estudiante auxiliarEst = arrayEst.get(i);
			
			totalEst += 1;
			if (auxiliarEst.getEdad() >= 6 &&  auxiliarEst.getEdad() <= 10 ){
				est6y10 += 1; 
			}
			
			if (auxiliarEst.getId().startsWith("TI")) {
					
					System.out.println("El estudiante : " + auxiliarEst.getNombre() + " Tiene " + auxiliarEst.getEdad() + " años de edad y esta en el grado " + auxiliarEst.getGrado() );
			}
			
			
		}
		
		System.out.println("El Total de estudiantes es:  " + Integer.toString(totalEst));
		System.out.println("El numero de estudiantes entre 6 y 10 años de edad es:  " + Integer.toString(est6y10));
		
		
	}
	
	public static void estudiantesPorGrado (ArrayList<Estudiante> arrayJardin, ArrayList<Estudiante> arrayPrimero, ArrayList<Estudiante> arraySegundo, ArrayList<Estudiante> arrayTercero, ArrayList<Estudiante> arrayCuarto, ArrayList<Estudiante> arrayQuinto ) {

		System.out.println("################ Estudiantes de Jardin ################");
		
		for (int i = 0;i< arrayJardin.size();i++) { 
			Estudiante auxiliarEst = arrayJardin.get(i);
					
			System.out.println("Nombre Estudiante : " + auxiliarEst.getNombre() + "  Edad " + auxiliarEst.getEdad() + " Identificación " + auxiliarEst.getId() );
		}
		
		System.out.println("################ Estudiantes de Primero ################");
		
		for (int i = 0;i< arrayPrimero.size();i++) { 
			Estudiante auxiliarEst = arrayPrimero.get(i);
					
			System.out.println("Nombre Estudiante : " + auxiliarEst.getNombre() + "  Edad " + auxiliarEst.getEdad() + " Identificación " + auxiliarEst.getId() );
		}
		
		System.out.println("################ Estudiantes de Segundo ################");
		
		for (int i = 0;i< arraySegundo.size();i++) { 
			Estudiante auxiliarEst = arraySegundo.get(i);
					
			System.out.println("Nombre Estudiante : " + auxiliarEst.getNombre() + "  Edad " + auxiliarEst.getEdad() + " Identificación " + auxiliarEst.getId() );
		}
		
		System.out.println("################ Estudiantes de Tercero ################");
		
		for (int i = 0;i< arrayTercero.size();i++) { 
			Estudiante auxiliarEst = arrayTercero.get(i);
					
			System.out.println("Nombre Estudiante : " + auxiliarEst.getNombre() + "  Edad " + auxiliarEst.getEdad() + " Identificación " + auxiliarEst.getId() );
		}
		
		System.out.println("################ Estudiantes de Cuarto ################");
		
		for (int i = 0;i< arrayCuarto.size();i++) { 
			Estudiante auxiliarEst = arrayCuarto.get(i);
					
			System.out.println("Nombre Estudiante : " + auxiliarEst.getNombre() + "  Edad " + auxiliarEst.getEdad() + " Identificación " + auxiliarEst.getId() );
		}
		
		System.out.println("################ Estudiantes de Quinto ################");
		
		for (int i = 0;i< arrayQuinto.size();i++) { 
			Estudiante auxiliarEst = arrayQuinto.get(i);
					
			System.out.println("Nombre Estudiante : " + auxiliarEst.getNombre() + "  Edad " + auxiliarEst.getEdad() + " Identificación " + auxiliarEst.getId() );
		}

	}
	
	
	public static void estudiantesQueReprueban (ArrayList<Estudiante> arrayEst ) {

		System.out.println("################ Estudiantes que reprueban el año ################");
		
		for (int i = 0;i< arrayEst.size();i++) { 
			Estudiante auxiliarEst = arrayEst.get(i);
			if (auxiliarEst.getAprobo().equals("N") ) {		
				System.out.println("Nombre Estudiante : " + auxiliarEst.getNombre() + "  Edad " + auxiliarEst.getEdad() + " Identificación " + auxiliarEst.getId() );
			}
		}
		
		
	}
	public static void actualizarArchivo (ArrayList<Estudiante> arrayEst)  {
		try {
			FileWriter file = new FileWriter("src/main/resources/data.txt");
			
			for (int i = 0;i< arrayEst.size();i++) { 
				Estudiante auxiliarEst = arrayEst.get(i);
				
				file.write(auxiliarEst.getId() + "," + auxiliarEst.getNombre() + "," + auxiliarEst.getEdad() + "," + auxiliarEst.getGrado() + "," + auxiliarEst.getAprobo() + "\r");
				
			}
			
			file.close();
			
		} catch (FileNotFoundException e) {
			System.out.println("El archivo no se encuentra " + e);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}
	
	public static String cadenaAleatoria(int longitud) {
	    // El banco de caracteres
	    String banco = "SN";
	    // La cadena en donde iremos agregando un carácter aleatorio
	    String cadena = "";
	    for (int x = 0; x < longitud; x++) {
	        int indiceAleatorio = numeroAleatorioEnRango(0, banco.length() - 1);
	        char caracterAleatorio = banco.charAt(indiceAleatorio);
	        cadena += caracterAleatorio;
	    }
	    return cadena;
	}
	
	public static int numeroAleatorioEnRango(int minimo, int maximo) {
        // nextInt regresa en rango pero con límite superior exclusivo, por eso sumamos 1
        return ThreadLocalRandom.current().nextInt(minimo, maximo + 1);
    }
				
		
			
	
}
